package diagrams.entity;

public enum LogicType {
    IF, WHILE, DO_WHILE, FOR, SWITCH,
    CASE, DEFAULT, ELSE, ELSE_IF, TRY,
    CATCH, FINALLY, THROW, CATCH_THROW,
    RETURN, BREAK, CONTINUE, GOTO, LABEL,
    FUNCTION, CLASS, INTERFACE, ENUM, ANNOTATION,
    ANONYMOUS_CLASS, LAMBDA, BLOCK, STATEMENT, EXPRESSION,
    VARIABLE, FIELD, METHOD, CONSTRUCTOR, PARAMETER,
    ARGUMENT, TYPE, LITERAL, OPERATOR, SEPARATOR,
    COMMENT, EMPTY, UNKNOWN
}
